import { getParleyConfig, isReasoningModel, extractJsonString, type ParleyConfig } from './parleyService';
import { validateSpec } from '../creator/spec';
import { exampleSpec } from '../creator/example';
export const creatorPrompt = `You build playable content for GameForge by returning ONE JSON CreationSpec, never JavaScript or external assets. Invent original layered procedural art and bounded gameplay graphs. Do not choose an existing enemy template. Every key in the example is required; no extra keys.
Units: pixels, milliseconds, radians, radians/second, pixels/second. Shapes are oriented UP at rotation 0; sword is a detailed blade/guard/grip silhouette. Shape kinds sword, polygon (3–24 normalized [-1,1] point pairs), ellipse, rect. Every shape optionally accepts layers:[{points:[[x,y],...],color:"#RRGGBB"}] (max8 nonrecursive polygon overlays,3–24 points each). Use these for flames on sword projectiles, runes and trim. Use layers and arbitrary polygons for original silhouettes, attached weapons, flames, wings. Components: 1–12 copies, radius 0–150, orbitSpeed +/-8, spin +/-12, x/y +/-150, width/height 4–160, contact damage 0–80, cooldown >=500. Maximum 16 components /32 instances. Orbit stays attached to a moving entity. Visual contact uses oriented bounds. Zero radius means attached component.
Entity types boss, enemy, mechanic. For a mechanic use visuals:[] and attacks:[] if it only defines statuses. Movement modes hover, pursuit, charge, stationary, speed 0–300, distance 60–400. Flying movement ignores gravity, steers around blocked space; Charge commits its heading toward the player when activated; use another move action after a timer to recover. Ground walking/terrain generation/inventory weapons/player stat changes are not supported. Be explicit about limits.
Attacks max 8: windup 400–5000; projectile speed 40–400, turnRate 0–2.5 (bounded homing; zero straight), lifetime 300–8000, damage 0–100, count 1–12, spread 0–6.28, burst 1–6, burstInterval 100–3000, orbitRadius 0–160, orbitSpeed +/-8, status null or status id. Projectiles use their own shape, rotate to travel, and collide with terrain. Graph fire actions queue a visible windup. Simultaneous projectiles capped at 96 across the session; 8 creations. Avoid budgets that intentionally truncate requested patterns.
Graph: max 8 states,32 rules,8 actions/rule. initial must be a state. Events timer, healthBelow, enter; rule state required; interval 500–30000; threshold 0–1 fraction of HP; once boolean. Actions exactly {type:'fire',attack:id}, {type:'state',state:id}, {type:'move',mode,speed}, {type:'orbit',speed}. No loops/recursion; transitions execute on next tick. Timers use active play time and reset on state entry. HealthBelow is normally once:true. Put attack cadence rules in every phase.
Statuses max 8, exact keys: id,label,color (#RRGGBB),icon (1–8 characters),sources (attack IDs in this spec and/or enemy-contact,enemy-projectile,generated-contact),amount (1–100),maximum (1–1000),decayDelay (0–30000),decayRate (.1–100 per second),duration (500–30000),damage (1–50),damageInterval (500–10000),resetOnActivation boolean,refresh ('refresh'|'ignore'),stacking:'none',death:'clear',respawn:'clear'. Each accepted damaging hit contributes once; damage-over-time never adds buildup. Meter appears on buildup/effect, disappears at zero and on removal. Label/color/icon define temporary HUD. No permanent stat changes.
Stats health 10–5000, contactDamage 0–100, contactCooldown 500–10000. Spawn distance 260–600, grace 1500–10000; runtime finds free space and rejects unsafe placement. Removal defeat-or-manual; lifetime session. IDs lowercase-kebab-case max48 chars; name max80. Summary max1000.
Extract ALL explicit user requirements as requirements:[{text,supported,evidence,limitation}]. Evidence is one or more dot paths into executable fields (e.g. visuals.1.count, attacks.0.projectile.turnRate). For unsupported requests set supported:false and explain the specific limitation. NEVER silently substitute. Requirements are checked before application. Preserve every existing requirement on edits unless the user changes it. The full previous spec is supplied for edits; return a complete replacement with same id, not a patch. Respect requested counts exactly. Include requested timers, phases, HUD and effects.
Example for schema structure (invent a different design matching the user, do not reuse this silhouette by default):\n${JSON.stringify(exampleSpec)}`;
export async function handleCreation(body: unknown, override?: Partial<ParleyConfig>, fetchFn: typeof fetch=fetch) {
 try {
  if(!body || typeof body!=='object')throw Error('Expected request object');
  const req=body as {prompt?:unknown;previous?:unknown};
  if(typeof req.prompt!=='string'||!req.prompt.trim()||req.prompt.length>6000) return {ok:false,statusCode:400,error:'Prompt must contain 1–6000 characters.'};
  const previous=req.previous==null?undefined:validateSpec(req.previous);
  const config={...getParleyConfig(),...override};
  if(!config.apiKey)return {ok:false,statusCode:401,error:'Missing server PARLEY_API_KEY. Configure .env and restart the updated project.'};
  const messages=[{role:'system',content:creatorPrompt},{role:'user',content:JSON.stringify({prompt:req.prompt,previous})}];
  let lastError='';
  for(let attempt=0;attempt<2;attempt++) {
   const res=await fetchFn(`${config.baseUrl}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${config.apiKey}`},body:JSON.stringify({model:config.model,messages,...(!isReasoningModel(config.model)?{temperature:.3}:{})}),signal:AbortSignal.timeout(120000)});
   if(!res.ok)return {ok:false,statusCode:res.status===429?429:502,error:res.status===401||res.status===403?'Parley rejected the server credentials.':`Parley request failed (HTTP ${res.status}). No changes applied.`};
   const data=await res.json();const content=data?.choices?.[0]?.message?.content;
   if(typeof content!=='string'||content.length>120000)throw Error('Parley returned an empty or oversized response');
   try {const spec=validateSpec(JSON.parse(extractJsonString(content)));if(previous&&spec.id!==previous.id)throw Error('Follow-up must preserve the selected creation ID');return {ok:true,statusCode:200,data:spec};}
   catch(e){lastError=e instanceof Error?e.message:'Invalid specification';messages.push({role:'assistant',content},{role:'user',content:`Validation failed: ${lastError}. Correct the full spec without dropping any explicit requirement. If unsupported, explain that limitation in requirements.`});}
  }
  return {ok:false,statusCode:422,error:lastError};
 }catch(e){return {ok:false,statusCode:422,error:e instanceof Error?e.message:'Creation failed; no changes applied.'};}
}
