import { useEffect, useRef, useState } from 'react';
import { SaveStore } from './sandbox/persistence';
import { startSandbox, type SandboxController, type SandboxHud, type Menu } from './sandbox/engine';
import { DEFAULT_WORLD, ITEMS, RECIPES, SKINS, OBJECTIVES, CHUNK, TILE, add, remove, count, craft, unlock, claim, newWorld, type ItemId, type SkinId, type WorldSettings } from './sandbox/model';
import { landmarks } from './sandbox/terrain';
import { downloadCsv } from './analytics';
import StatsPanel from './components/StatsPanel';
let opening: Promise<SaveStore> | undefined;
function SkinPortrait({ id }: {
    id: SkinId;
}) { const skin = SKINS.find(s => s.id === id)!; return <svg viewBox="0 0 80 90" className="skin-art" aria-label={skin.name}><ellipse cx="40" cy="84" rx="26" ry="4" fill="#101d2b"/>{['knight', 'wanderer'].includes(id) && <path d="M24 30 L11 76 L46 67 L55 33" fill={id === 'knight' ? '#392a53' : '#6f5c9c'}/>}<path d="M24 35 H57 V62 H24Z M18 36 H25 V58 H18Z M57 36 H64 V58 H57Z" fill={skin.color}/><path d="M29 62 H38 V80 H25V74H29Z M45 62H54V74H58V80H45Z" fill="#96a9ad"/><path d="M27 10H56V32H27Z" fill={skin.color}/><path d="M35 18H59V26H35Z" fill="#d6fff2"/><path d="M34 40H47V59H34Z" fill="#294557"/>{id === 'ranger' && <path d="M22 12H64V18H22Z M31 5H53V12H31Z M10 38H17V65H10Z" fill="#9d7755"/>}{id === 'wanderer' && <path d="M25 14L29 0L36 12L43 0L48 12L55 0L59 14Z" fill="#d5bdff"/>}{id === 'neon' && <path d="M21 3H24V24H21Z M60 3H63V24H60Z M12 40H18V63H12Z M39 43H42V58H39Z" fill="#a8ffed"/>}{id === 'knight' && <path d="M20 0L30 14H23Z M63 0L54 14H61Z M18 31H31V39H18Z M54 31H68V39H54Z" fill="#c593b5"/>}{id === 'automaton' && <><path d="M22 8H62V31H22Z" fill="#a39260"/><path d="M29 17H37V23H29Z M49 17H57V23H49Z" fill="#beffee"/><circle cx="41" cy="48" r="6" fill="#f7e6a1"/></>}</svg>; }
const EMPTY: SandboxHud = { health: 100, mana: 100, status: 'paused', biome: 'Verdant frontier', selected: 1, message: 'Explore Lumen frontier', nearBase: true, fps: 0, chunks: 0, enemies: 0, bodies: 0, x: 288, y: 504, recall: 0 };
export default function App() {
    const [store, setStore] = useState<SaveStore | null>(null), [revision, setRevision] = useState(0), [hud, setHud] = useState(EMPTY), [menu, setMenu] = useState<Menu>(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [pending, setPending] = useState(false), [slot, setSlot] = useState<number | null>(null), [settings, setSettings] = useState<WorldSettings>({ ...DEFAULT_WORLD }), [sellId, setSellId] = useState<ItemId>('stone'), [quantity, setQuantity] = useState(1), [debug, setDebug] = useState(false), [shake, setShake] = useState(true);
    const host = useRef<HTMLDivElement>(null), frame = useRef<HTMLDivElement>(null), engine = useRef<SandboxController | null>(null), dialog = useRef<HTMLElement | null>(null);
    useEffect(() => { let alive = true; opening ??= SaveStore.open(); void opening.then(s => { if (alive)
        setStore(s); }).catch(e => { if (alive)
        setError(String(e)); }); return () => { alive = false; }; }, []);
    useEffect(() => { if (!store)
        return; store.onChange = () => setRevision(v => v + 1); store.onError = m => setNotice(m); return () => { store.onChange = undefined; store.onError = undefined; }; }, [store]);
    const active = store?.data.active;
    useEffect(() => { if (!store || !host.current)
        return; let alive = true; try {
        engine.current = startSandbox(host.current, store, h => { if (alive)
            setHud(h); }, m => { if (alive)
            setMenu(m); });
    }
    catch (e) {
        setError(String(e));
    } return () => { alive = false; engine.current?.destroy(); engine.current = null; }; }, [store, active]);
    useEffect(() => { engine.current?.setShake(shake); }, [shake, active]);
    useEffect(() => { if (menu)
        dialog.current?.focus(); }, [menu]);
    void revision;
    const open = (m: Menu) => { engine.current?.pause(); setMenu(m); setSlot(null); setNotice(''); };
    const act = async (fn: () => Promise<unknown>) => { if (pending)
        return; setPending(true); try {
        const result = await fn();
        if (typeof result === 'string')
            setNotice(result);
    }
    catch (e) {
        setNotice(e instanceof Error ? e.message : String(e));
    }
    finally {
        setPending(false);
    } };
    const close = () => { setMenu(null); setSlot(null); engine.current?.resume(); };
    if (!store)
        return <main className="loading"><p className="eyebrow">GAMEFORGE / LUMEN FRONTIER</p><h1>{error ? 'Your save is safe.' : 'Preparing your expedition…'}</h1><p>{error || 'Opening local world storage.'}</p>{error && <p>Close other game tabs and reload. Incompatible saves are never silently replaced.</p>}</main>;
    const world = store.world, profile = store.data.profile;
    const transact = (fn: Parameters<SaveStore['transact']>[0]) => act(() => store.transact(fn));
    return <main className="sandbox-app"><header className="sandbox-header"><div className="brand">GAME<span>FORGE</span><small>LUMEN FRONTIER · A WORLD TO DISCOVER</small></div><div className="header-right"><span className="ai-status">AI generation not connected</span><button onClick={downloadCsv} title="Export play data as CSV for SIGNAL analysis">Export to SIGNAL</button><button onClick={() => open('worlds')}>Worlds & creation</button></div></header>
 <section className="world-shell" ref={frame}><div className="world-hud"><div className="vital"><span>HEALTH <b>{hud.health}</b></span><meter min="0" max="100" value={hud.health}/></div><div className="vital mana"><span>MANA <b>{hud.mana}</b></span><meter min="0" max="100" value={hud.mana}/></div><div className="location"><strong>{hud.biome}</strong><small>{world.name} · {Math.floor(hud.y / TILE)}m depth</small></div><div className="coins">◈ {world.coins}<small>COINS</small></div><button onPointerDown={e => e.preventDefault()} onClick={() => { if (hud.status === 'paused' && !menu)
        engine.current?.resume();
    else {
        engine.current?.pause();
        setMenu(null);
    } }}>{hud.status === 'paused' && !menu ? 'Play' : 'Pause'}</button><button aria-label="Fullscreen" onClick={() => { if (document.fullscreenElement)
        void document.exitFullscreen();
    else
        void frame.current?.requestFullscreen().catch(() => setNotice('Fullscreen is unavailable here.')); }}>⛶</button></div>
 <div className="viewport"><div ref={host} className="game-host" aria-label="Lumen frontier sandbox game"/>{import.meta.env.DEV && debug && <div className="debug">{hud.fps} FPS · {hud.chunks}/15 chunks · {hud.enemies}/12 enemies · {hud.bodies} terrain bodies · {Math.floor(hud.x)},{Math.floor(hud.y)}</div>}
 {!menu && hud.status !== 'playing' && <div className="overlay"><div><p className="eyebrow">{hud.status === 'dead' ? 'BEACON SIGNAL RECEIVED' : 'LUMEN OUTPOST / EXPEDITION PAUSED'}</p><h2>{hud.status === 'dead' ? 'Your journey continues.' : 'A strange new frontier.'}</h2><p>{hud.status === 'dead' ? 'Respawn at the outpost. Your inventory, coins, and skins are retained.' : 'Explore living hills and buried ruins. Gather, craft, and make this planet your own.'}</p><button className="primary" onClick={() => hud.status === 'dead' ? engine.current?.respawn() : engine.current?.resume()}>{hud.status === 'dead' ? 'Return to checkpoint · R' : 'Continue expedition →'}</button><p className="start-tip">E gathers trees and herbs · J uses your selected tool · 1–8 selects equipment</p></div></div>}
 {menu && <div className="menu-shade"><section ref={dialog} tabIndex={-1} className="game-menu" aria-label={`${menu} panel`}><div className="menu-heading"><div><p className="eyebrow">EXPEDITION PAUSED</p><h2>{{ inventory: 'Pack & equipment', crafting: 'Outpost crafting', skins: 'Explorer wardrobe', objectives: 'Earn coins', shop: 'Salvage exchange', map: 'Survey map', worlds: 'Your worlds', settings: 'Expedition settings', stats: 'Player stats & charts' }[menu]}</h2></div><button onClick={close} disabled={pending}>Close & play ×</button></div><div className="menu-content">
 {menu === 'inventory' && <><p>Click an item, then a slot to move or swap it. The first eight slots are your hotbar. Resources belong to this world.</p><div className="inventory-grid">{world.inventory.map((s, i) => <button key={i} className={`item-slot ${i < 8 ? 'quick' : ''} ${slot === i ? 'chosen' : ''}`} title={s ? `${ITEMS[s.id].name} ×${s.count} — ${ITEMS[s.id].description}` : `Empty slot ${i + 1}`} onClick={() => { if (slot === null)
            setSlot(i);
        else {
            const source = slot;
            void transact((_b, w) => { [w.inventory[source], w.inventory[i]] = [w.inventory[i], w.inventory[source]]; });
            setSlot(null);
        } }}><small>{i + 1}</small>{s && <><span>{ITEMS[s.id].icon}</span><em>{s.count}</em><label>{ITEMS[s.id].name}</label></>}</button>)}</div>{slot !== null && world.inventory[slot] && <p>{ITEMS[world.inventory[slot]!.id].description}</p>}</>}
 {menu === 'crafting' && <><p>{hud.nearBase ? 'Workbench and forge connected.' : 'Return to the outpost to use the workbench and forge.'} Crafted items go into your pack; move equipment into a hotbar slot.</p><div className="recipe-grid">{RECIPES.map(r => { const enough = Object.entries(r.ingredients).every(([id, n]) => count(world.inventory, id as ItemId) >= n); return <article key={r.id}><div className="recipe-title"><span>{ITEMS[r.output.id].icon}</span><h3>{r.name} <small>×{r.output.count}</small></h3></div><p>{r.station}</p><div className="ingredients">{Object.entries(r.ingredients).map(([id, n]) => <span key={id} className={count(world.inventory, id as ItemId) >= n ? 'available' : ''}>{ITEMS[id as ItemId].name} {count(world.inventory, id as ItemId)}/{n}</span>)}</div><button disabled={!enough || !hud.nearBase || pending} onClick={() => void transact((_b, w) => craft(w, r.id, hud.nearBase))}>Craft {ITEMS[r.output.id].name}</button></article>; })}</div></>}
 {menu === 'skins' && <><p>Cosmetics belong to your local player profile and work across worlds. Coins are spent from this world. Skins never change combat stats.</p><div className="skin-grid">{SKINS.map(s => { const owned = profile.owned.includes(s.id), equipped = profile.equipped === s.id; return <article key={s.id} className={equipped ? 'equipped' : ''}><SkinPortrait id={s.id}/><h3>{s.name}</h3><p>{s.description}</p><button disabled={equipped || pending} onClick={() => void transact((b) => { if (owned) {
            if (!b.profile.owned.includes(s.id))
                throw new Error('Unlock this skin first.');
            b.profile.equipped = s.id;
            return `${s.name} equipped`;
        } return unlock(b, s.id); })}>{equipped ? 'Equipped' : owned ? 'Equip · free' : `Unlock · ${s.price} coins`}</button></article>; })}</div></>}
 {menu === 'objectives' && <><p>One-time objectives for this world. Progress comes from exploring, mining, fighting, and crafting. Claim each reward once.</p><div className="objective-list">{OBJECTIVES.map(o => { const done = world.progress[o.id] >= o.total, claimed = world.claimed.includes(o.id); return <article key={o.id}><div><h3>{o.name}</h3><p>{Math.min(world.progress[o.id], o.total)} / {o.total} · {claimed ? 'Claimed' : done ? 'Complete' : 'Active'}</p><progress max={o.total} value={world.progress[o.id]}/></div><button disabled={!done || claimed || pending} onClick={() => void transact((_b, w) => claim(w, o.id))}>{claimed ? 'Reward claimed' : `Claim ${o.reward} coins`}</button></article>; })}</div></>}
 {menu === 'shop' && <><p>{hud.nearBase ? 'Sell spare materials at the outpost terminal.' : 'Return to the outpost terminal to sell resources.'}</p><p>Uncollected combat resources are safely held here when your pack is full.</p><button disabled={!hud.nearBase || pending} onClick={() => void transact((_b, w) => { let total = 0; for (const [id, n] of Object.entries(w.pendingLoot ?? {})) {
            if (n && add(w.inventory, id as ItemId, n)) {
                delete w.pendingLoot[id as ItemId];
                total += n;
            }
        } return total ? `Collected ${total} held resources` : 'No held resources, or your inventory is still full.'; })}>Collect held resources ({Object.values(world.pendingLoot ?? {}).reduce((n, v) => n + (v ?? 0), 0)})</button><div className="sell-form"><label>Resource<select value={sellId} onChange={e => setSellId(e.target.value as ItemId)}>{(Object.keys(ITEMS) as ItemId[]).filter(id => ITEMS[id].value > 0 && !['tool', 'weapon'].includes(ITEMS[id].category)).map(id => <option value={id} key={id}>{ITEMS[id].name} · {count(world.inventory, id)} in pack</option>)}</select></label><label>Quantity<input type="number" min="1" max="999" value={quantity} onChange={e => setQuantity(Number(e.target.value))}/></label><p>{quantity} × {ITEMS[sellId].value} = <strong>{quantity * ITEMS[sellId].value} coins</strong></p><button className="primary" disabled={!hud.nearBase || pending || !Number.isInteger(quantity) || quantity < 1 || count(world.inventory, sellId) < quantity} onClick={() => void transact((_b, w) => { if (!hud.nearBase || !Number.isSafeInteger(quantity) || quantity < 1 || !remove(w.inventory, sellId, quantity))
            throw new Error('Sale unavailable.'); const value = quantity * ITEMS[sellId].value; w.coins += value; return `Sold ${quantity} ${ITEMS[sellId].name} for ${value} coins`; })}>Sell {quantity} for {quantity * ITEMS[sellId].value} coins</button></div></>}
 {menu === 'map' && <><p>Only surveyed chunks are shown. ◈ marks discovered caches; ● marks the outpost. Use Recall to return safely.</p><svg viewBox="0 0 620 300" className="survey-map" role="img" aria-label="Explored terrain map">{Object.entries(world.explored).slice(-1000).map(([key, b]) => { const [x, y] = key.split(',').map(Number), cx = Math.floor(hud.x / (CHUNK * TILE)); return <g key={key}><rect x={300 + (x - cx) * 22} y={y * 45 + 20} width="21" height="44" fill={b === 'Crystal depths' ? '#706195' : b === 'Rust wastes' ? '#9e7660' : '#608b79'}/>{landmarks(world.settings, x).some(l => Math.floor(l.y / CHUNK) === y) && <text x={305 + (x - cx) * 22} y={y * 45 + 42} fill="#f5d08f" fontSize="10">◈</text>}{x === 0 && y === 0 && <text x={305 + (x - cx) * 22} y="38" fill="#fff">●</text>}</g>; })}<circle cx={311} cy={Math.floor(hud.y / (CHUNK * TILE)) * 45 + 42} r="4" fill="#fff"/></svg><button onClick={() => { setMenu(null); engine.current?.recall(); }}>Recall to outpost · 2.5 seconds</button></>}
 {menu === 'worlds' && <><p>Worlds store their own items, coins, objectives, and terrain changes. Skins are shared. Saves live in this browser only; they are not cloud-synced.</p><div className="world-list">{Object.values(store.data.worlds).map(w => <button key={w.id} disabled={w.id === active || pending} onClick={() => void act(async () => { await engine.current?.save(); await store.transact(b => { b.active = w.id; }); setMenu(null); })}>{w.name} {w.id === active ? '· Current' : '· Load world'}</button>)}</div><details><summary>Create a new world · existing worlds are kept</summary><div className="generation-form"><label>Seed<input value={settings.seed} maxLength={80} onChange={e => setSettings({ ...settings, seed: e.target.value })}/></label><label>Difficulty<select value={settings.difficulty} onChange={e => setSettings({ ...settings, difficulty: e.target.value as WorldSettings['difficulty'] })}><option value="explorer">Explorer</option><option value="standard">Standard</option></select></label>{(['roughness', 'caves', 'abundance'] as const).map(key => <label key={key}>{key}<input type="range" min="0.6" max="1.4" step="0.1" value={settings[key]} onChange={e => setSettings({ ...settings, [key]: Number(e.target.value) })}/></label>)}<button className="primary" disabled={pending} onClick={() => void act(async () => { await engine.current?.save(); await store.transact(b => { const w = newWorld(crypto.randomUUID(), settings); b.worlds[w.id] = w; b.active = w.id; }); setMenu(null); })}>Create new world</button></div></details><p>Terrain settings are fixed once a world is created. New terrain settings require a new world.</p><details><summary>AI creation · not connected</summary><textarea placeholder="Describe a future world…"/><button disabled>Generate world</button><p>Future prompts will adjust supported settings, not execute generated code.</p></details><div className="save-actions"><button onClick={() => void act(async () => { await engine.current?.save(); const url = URL.createObjectURL(new Blob([store.export()], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'gameforge-worlds.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); return 'Save file exported'; })}>Export all local saves</button><label className="import-label">Import save file<input type="file" accept="application/json" onChange={e => { const f = e.target.files?.[0]; if (f)
            void act(async () => { if (f.size > 20000000)
                throw new Error('Save file is too large.'); const imported = JSON.parse(await f.text()); await engine.current?.save(); await store.import(imported); setMenu(null); return 'Imported save'; }); }}/></label></div><p>Import merges worlds and cosmetic ownership. Existing worlds are preserved as separate copies if IDs match.</p></>}
 {menu === 'stats' && <StatsPanel world={world} />}
 {menu === 'settings' && <><label className="check"><input type="checkbox" checked={shake} onChange={e => setShake(e.target.checked)}/>Camera shake</label>{import.meta.env.DEV && <label className="check"><input type="checkbox" checked={debug} onChange={e => setDebug(e.target.checked)}/>Show performance overlay</label>}<p>Controls: A/D or arrows move; Space jumps; J or left click attacks/mines; F or right click places; E interacts; 1–8 selects; H recalls; I inventory; C crafting; M map; Escape pauses.</p><button onClick={() => void act(async () => { await engine.current?.save(); return 'Saved to this browser'; })}>Save now</button></>}
 </div>{notice && <div className="menu-notice" role="status">{notice}</div>}</section></div>}
 </div><div className="hotbar">{world.inventory.slice(0, 8).map((s, i) => <button key={i} className={hud.selected === i ? 'selected' : ''} onPointerDown={e => e.preventDefault()} onClick={() => engine.current?.select(i)} title={s ? `${ITEMS[s.id].name} ×${s.count} — ${ITEMS[s.id].description}` : 'Empty hotbar slot'}><kbd>{i + 1}</kbd><span>{s ? ITEMS[s.id].icon : '·'}</span><small>{s?.count ?? ''}</small><label>{s ? ITEMS[s.id].name : 'Empty'}</label></button>)}</div><div className="reward-line" role="status"><span>✦</span>{hud.recall > 0 ? `Recall ${Math.round(hud.recall * 100)}%` : notice && !menu ? notice : hud.message}</div></section>
 <nav className="game-nav">{([['inventory', 'Inventory · I'], ['crafting', 'Crafting · C'], ['skins', 'Skins'], ['objectives', 'Earn coins'], ['shop', 'Sell resources'], ['map', 'Map · M'], ['stats', 'Stats'], ['settings', 'Settings']] as const).map(([id, title]) => <button key={id} onClick={() => open(id)}>{title}</button>)}<button onClick={() => { setMenu(null); engine.current?.recall(); }}>Recall · H</button></nav><div className="guide"><span><kbd>A D</kbd> Move <kbd>SPACE</kbd> Jump <kbd>J</kbd> Use tool <kbd>F</kbd> Place <kbd>E</kbd> Gather / interact</span><span>Next: {OBJECTIVES.find(o => !world.claimed.includes(o.id))?.name ?? 'Explore beyond the frontier'}</span></div>{error && <p role="alert">{error}</p>}</main>;
}
